#!/usr/bin/env bash
# gen-types.sh — regenerate src/data/database.types.ts from the migrations themselves.
#
# Spins an ephemeral Postgres cluster, applies every migration in order, and runs the
# postgres-meta TypeScript generator (the same engine behind `supabase gen types`) against
# it. No Docker and no live Supabase project needed — the migrations directory is the
# single source of truth, so the generated types can never drift ahead of or behind a
# remote database's state.
#
# Usage: scripts/gen-types.sh            # writes src/data/database.types.ts
#
# Known cosmetic divergence from a hosted Supabase project: on vanilla Postgres the
# migrations install pgcrypto/vector into `public` (hosted Supabase pre-installs them in
# `extensions`), so a few extension functions (gen_salt, dearmor, …) appear as extra
# entries in the generated Functions map. They are additive noise — nothing calls them —
# and filtering the generator's output by hand would be worse than carrying them.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MIG_DIR="$SCRIPT_DIR/../supabase/migrations"
OUT_FILE="$SCRIPT_DIR/../src/data/database.types.ts"

PGPORT="${GEN_TYPES_PGPORT:-5498}"
PGMETA_PORT="${GEN_TYPES_PGMETA_PORT:-8766}"
WORK="$(mktemp -d)"
PGMETA_PID=""

PG_BIN="$(ls -d /usr/lib/postgresql/*/bin 2>/dev/null | sort -V | tail -1 || true)"
[[ -n "$PG_BIN" ]] && export PATH="$PG_BIN:$PATH"
command -v initdb >/dev/null || { echo "initdb not found — install postgresql" >&2; exit 1; }

pg_user_exec() {
  if [[ $(id -u) -eq 0 ]]; then
    su -s /bin/bash postgres -c "PATH=\"$PATH\"; $1"
  else
    bash -c "$1"
  fi
}

cleanup() {
  [[ -n "$PGMETA_PID" ]] && kill "$PGMETA_PID" >/dev/null 2>&1 || true
  pg_user_exec "pg_ctl -D '$WORK/data' -m immediate stop" >/dev/null 2>&1 || true
  rm -rf "$WORK"
}
trap cleanup EXIT

# ---------- ephemeral cluster (TCP: postgres-meta connects over it) ----------
mkdir -p "$WORK/sock"
[[ $(id -u) -eq 0 ]] && chown -R postgres:postgres "$WORK"
pg_user_exec "initdb -D '$WORK/data' -A trust" >/dev/null
pg_user_exec "pg_ctl -D '$WORK/data' -o \"-p $PGPORT -k '$WORK/sock' -c listen_addresses=127.0.0.1\" -w -l '$WORK/pg.log' start" >/dev/null
pg_user_exec "createdb -h 127.0.0.1 -p $PGPORT -U postgres atlas_types"
DB_URL="postgres://postgres@127.0.0.1:$PGPORT/atlas_types"

for f in "$MIG_DIR"/*.sql; do
  psql "$DB_URL" -X -q -v ON_ERROR_STOP=1 -f "$f" >/dev/null
done
echo "applied $(ls "$MIG_DIR"/*.sql | wc -l) migrations"

# ---------- postgres-meta typegen ----------
mkdir -p "$WORK/pgmeta"
(cd "$WORK/pgmeta" && npm init -y >/dev/null 2>&1 \
  && npm install --no-audit --no-fund @supabase/postgres-meta >/dev/null 2>&1)

(cd "$WORK/pgmeta" && \
  PG_META_DB_URL="$DB_URL" PG_META_PORT="$PGMETA_PORT" \
  node node_modules/@supabase/postgres-meta/dist/server/server.js \
  > "$WORK/pgmeta.log" 2>&1) &
PGMETA_PID=$!

for _ in $(seq 1 30); do
  if curl -sf "http://127.0.0.1:$PGMETA_PORT/health" >/dev/null 2>&1 \
     || curl -sf "http://127.0.0.1:$PGMETA_PORT/generators/typescript?included_schemas=public" -o /dev/null 2>/dev/null; then
    break
  fi
  sleep 0.5
done

curl -sf "http://127.0.0.1:$PGMETA_PORT/generators/typescript?included_schemas=public" \
  -o "$WORK/types.ts" \
  || { echo "typegen request failed; postgres-meta log follows" >&2; tail -20 "$WORK/pgmeta.log" >&2; exit 1; }

grep -q "export type Database" "$WORK/types.ts" \
  || { echo "typegen output missing Database type" >&2; exit 1; }

{
  echo "// Generated by scripts/gen-types.sh from supabase/migrations — do not edit by hand."
  echo "// Regenerate after adding a migration: npm run gen:types"
  cat "$WORK/types.ts"
} > "$OUT_FILE"

echo "wrote $OUT_FILE ($(wc -l < "$OUT_FILE") lines)"
