-- Real disposable Postgres boundary probes; fixtures generated by the TS calculator.
create function pg_temp.pricing_assert(ok boolean,msg text) returns void language plpgsql as $$
begin if ok is distinct from true then raise exception 'ASSERT PRICING/BILL: %',msg; end if; end $$;
create function pg_temp.pricing_reject(command text,pattern text) returns void language plpgsql as $$
begin
  begin execute command; exception when others then if sqlerrm not like pattern then raise; end if; return; end;
  raise exception 'ASSERT PRICING/BILL expected rejection: %',pattern;
end $$;
do $$
declare
  company uuid:='63000000-0000-4000-8000-000000000001'; account uuid:='63000000-0000-4000-8000-000000000002';
  product uuid:='63000000-0000-4000-8000-000000000003'; c jsonb:=current_setting('test.pricing_config')::jsonb;
  a jsonb:=current_setting('test.pricing_a')::jsonb; b jsonb:=current_setting('test.pricing_b')::jsonb;
  forged jsonb; version_id uuid; next_version uuid; source uuid; da uuid; db uuid; line_id uuid; ra jsonb; rb jsonb; retry jsonb; saved jsonb;
  revision timestamptz:='2026-10-02T09:00:00+13:00';
begin
  insert into orgs(id,slug,display_name) values(company,'pricing-fixture','Synthetic pricing');
  insert into accounts(id,org_id,name) values(account,company,'Synthetic retailer');
  insert into products(id,org_id,sku,display_name) values(product,company,'WIDGET','Synthetic widget');
  version_id:=save_pricing_version(company,0,c,'fixture-operator','Synthetic initial version');
  perform pg_temp.pricing_assert(version_id=save_pricing_version(company,0,c,'fixture-operator','Synthetic initial version'),'save retry stable');
  perform activate_pricing_version(company,version_id,1,'fixture-operator','Synthetic activation');
  perform pg_temp.pricing_reject(format('select save_pricing_version(%L,0,%L,%L,%L)',company,c||'{"version":"stale"}','operator','stale'),'%%stale pricing revision%%');
  perform pg_temp.pricing_reject(format('update pricing_versions set reason=%L where id=%L','changed',version_id),'%%append-only%%');
  perform assert_pricing_snapshot(c,a); perform assert_pricing_snapshot(c,b);
  forged:=jsonb_set(a,'{lines,0,unitPrice}','"1"');
  forged:=jsonb_set(forged,'{lines,0,lineAmount}','"40"');
  forged:=jsonb_set(forged,'{subtotal}','"40"');forged:=jsonb_set(forged,'{tax,amount}','"66"');forged:=jsonb_set(forged,'{total}','"506"');
  perform pg_temp.pricing_reject(format('select assert_pricing_snapshot(%L,%L)',c,forged),'%%configured unit price mismatch%%');
  perform pg_temp.pricing_reject(format('select assert_pricing_snapshot(%L,%L)',c,a #- '{terms,dueDate}'),'%%terms snapshot mismatch%%');
  perform pg_temp.pricing_reject(format('select assert_pricing_snapshot(%L,%L)',c,jsonb_set(a,'{freight,amount}','"0"')),'%%configured freight amount mismatch%%');
  perform pg_temp.pricing_reject(format('select assert_pricing_snapshot(%L,%L)',c,jsonb_set(a,'{pricingAt}','"2027-01-01T00:00:00Z"')),'%%calculation contract mismatch%%');
  insert into dispatch_sources(org_id,provider,connection_key) values(company,'synthetic','fixture') returning id into source;
  da:=project_dispatch(company,source,'dispatch-a','order-100',revision,'succeeded',null,
    '[{"source_line_key":"original","order_line_key":"order-line","item_key":"WIDGET","quantity":40,"ordered_quantity":100}]',null,'{}',revision);
  db:=project_dispatch(company,source,'dispatch-b','order-100',revision,'succeeded',null,
    '[{"source_line_key":"original","order_line_key":"order-line","item_key":"WIDGET","quantity":60,"ordered_quantity":100}]',null,'{}',revision);
  select id into line_id from dispatch_lines where dispatch_id=da;
  a:=jsonb_set(jsonb_set(a,'{lines,0,lineId}',to_jsonb(line_id::text)),'{input,lines,0,lineId}',to_jsonb(line_id::text));
  select id into line_id from dispatch_lines where dispatch_id=db;
  b:=jsonb_set(jsonb_set(b,'{lines,0,lineId}',to_jsonb(line_id::text)),'{input,lines,0,lineId}',to_jsonb(line_id::text));
  execute 'set local role service_role';
  perform pg_temp.pricing_reject(format('select draft_dispatch_invoice(%L,%L,%L,%L,%L,%L,%L)',company,source,da,revision,version_id,forged,'#synthetic-100'),'%%configured unit price mismatch%%');
  perform pg_temp.pricing_reject(format('select draft_dispatch_invoice(%L,%L,%L,%L,%L,%L,%L)',company,source,da,revision,version_id,a #- '{terms,dueDate}','#synthetic-100'),'%%terms snapshot mismatch%%');
  perform pg_temp.pricing_reject(format('select draft_dispatch_invoice(%L,%L,%L,%L,%L,%L,%L)',company,source,da,revision,version_id,jsonb_set(a,'{input,dispatchAt}','"2026-10-03T00:00:00Z"'),'#synthetic-100'),'%%authoritative dispatch time%%');
  execute 'reset role';
  if to_regprocedure('publish_platform_event(uuid,jsonb,text,text[])') is null then
    perform pg_temp.pricing_reject(format('select draft_dispatch_invoice(%L,%L,%L,%L,%L,%L,%L)',company,source,da,revision,version_id,a,'#synthetic-100'),'%%publish_platform_event%%');
    perform pg_temp.pricing_assert(not exists(select 1 from dispatch_invoice_parts where dispatch_id=da),'missing shared service rolls back allocation');
    perform pg_temp.pricing_assert(not exists(select 1 from invoices where org_id=company),'missing shared service rolls back invoice');
    raise notice 'BILL success/concurrency gate BLOCKED: shared EVENT helper is absent; no success claimed';
    return;
  end if;
  ra:=draft_dispatch_invoice(company,source,da,revision,version_id,a,'#synthetic-100');
  rb:=draft_dispatch_invoice(company,source,db,revision,version_id,b,'#synthetic-100');
  saved:=(select snapshot from invoice_calculation_snapshots where id=(ra->>'snapshotId')::uuid);
  perform pg_temp.pricing_assert((select sum(quantity)=100 and count(*)=2 from dispatch_allocations where org_id=company),'40/60 exactly once');
  perform pg_temp.pricing_assert((select invoice_number like '%A' and total_cents=37260 from invoices where id=(ra->>'invoiceId')::uuid),'part A identity/amount');
  perform pg_temp.pricing_assert((select invoice_number like '%B' and total_cents=55890 from invoices where id=(rb->>'invoiceId')::uuid),'part B identity/amount');
  for n in 1..3 loop
    retry:=draft_dispatch_invoice(company,source,da,revision,version_id,a,'#synthetic-100');
    perform pg_temp.pricing_assert(retry->>'invoiceId'=ra->>'invoiceId' and (retry->>'reused')::boolean,'retry stable');
  end loop;
  c:=jsonb_set(jsonb_set(jsonb_set(c,'{version}','"v2"'),'{effectiveFrom}','"2026-10-03T00:00:00+13:00"'),'{tiers,0,unitPrice}','"1200"');
  next_version:=save_pricing_version(company,1,c,'fixture-operator','Synthetic price change');
  perform activate_pricing_version(company,next_version,2,'fixture-operator','Synthetic price change');
  retry:=draft_dispatch_invoice(company,source,da,revision,next_version,'{}','#synthetic-100');
  perform pg_temp.pricing_assert(retry->>'invoiceId'=ra->>'invoiceId','retry does not recalculate after price change');
  perform pg_temp.pricing_assert((select snapshot=saved from invoice_calculation_snapshots where id=(ra->>'snapshotId')::uuid),'historical snapshot unchanged');
  perform pg_temp.pricing_reject(format('update invoices set due_at=now() where id=%L',ra->>'invoiceId'),'%%immutable%%');
  perform pg_temp.pricing_reject(format('update invoice_lines set unit_price_cents=1 where invoice_id=%L',ra->>'invoiceId'),'%%immutable%%');
end $$;
